version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
  aws-s3: circleci/aws-s3@3.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
machine:
  services: docker
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker: 
          version: 19.03.13
      - run: docker build -t reactdevimage -f ./client/Dockerfile.dev ./client/
      - run: docker run -it reactdevimage npm run test -- --coverage
      - run: docker build -t s4sarang/multi-client ./client; docker build -t s4sarang/multi-nginx ./nginx; docker build -t s4sarang/multi-server ./server; docker build -t s4sarang/multi-worker ./worker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push s4sarang/multi-client
      - run: docker push s4sarang/multi-nginx
      - run: docker push s4sarang/multi-server
      - run: docker push s4sarang/multi-worker
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-region: AWS_DEFAULT_REGION 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          from: ./ 
          to: s3://elasticbeanstalk-us-east-2-408677271841/multi-docker
      
workflows:
  running-tests:
    jobs:
      - build
      - aws-elastic-beanstalk/deploy:
            environment-name: Multidocker-env
            application-name: multi-docker
            filters:
              branches:
                only: main 
    