version: 2.1
machine:
  services: docker
jobs:
  working_directory: /app
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker: 
          version: 19.03.13 
      - run: ls; pwd; ls ../;
      - run: cd project; ls; 
      #- run: docker build -t reactdevimage -f Dockerfile.dev .
      #- run: docker run -it reactdevimage npm run test -- --coverage
      #- run: docker build -t multi-client ../client
workflows:
  running-tests:
    jobs:
      - build